# CodeRabbit configuration file
reviews:
  # Review settings
  high_level_summary: true
  poem: false
  review_status: true
  collapse_empty_files: true

  # Language specific settings
  auto_review:
    enabled: true
    drafts: false

  # File patterns to ignore
  path_filters:
    - '!**/*.md'
    - '!**/package-lock.json'
    - '!**/yarn.lock'
    - '!**/*.min.js'
    - '!**/dist/**'
    - '!**/build/**'
    - '!**/node_modules/**'

  # Focus areas
  focus_areas:
    - 'Performance issues'
    - 'Security vulnerabilities'
    - 'Code maintainability'
    - 'Best practices violations'
    - 'Type safety issues'
    - 'React/TypeScript patterns'

chat:
  # Chat settings
  auto_reply: false

# Language specific rules
language_settings:
  typescript:
    - 'Check for proper TypeScript typing'
    - 'Validate React hooks usage'
    - 'Review component patterns'

  javascript:
    - 'Check for modern JavaScript features'
    - 'Validate async/await usage'
